
services:
  mongo:
    image: mongo:6
    restart: always
    container_name: helpdesk-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    restart: always
    container_name: helpdesk-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
